### ISSUE TITLE
Future of sync?

### ISSUE THREAD

**Issue by pdimov** [boostorg/sync#8]
What's the plan about it? It lingers as a submodule on develop but not on master. Is it ever going to be released?

**Comment by Lastique** [comment]
This is totally my fault. I was going to allocate time to write some docs for it and then ask to include it in a Boost release, but never got around to do it. I still want to do it as I think there are useful tools in Boost.Sync, but given the history I'm not sure when I will be able to do it.

We could release it as is, I guess... The tests are running, and as far as I can tell they are mostly passing.

**Comment by pdimov** [comment]
Yes but we'll need some sort of a review first, and at least some explanation what it is and what it's for, if only in a README.md form. :-)

**Comment by jeking3** [comment]
Would the goal be to move synchronization primitives out of Boost.Thread and use these instead?  I agree, a README would be nice. :)  I can send in a PR for CMT flavor CI if you'd like.

**Comment by Lastique** [comment]
> Would the goal be to move synchronization primitives out of Boost.Thread and use these instead?

One of the goals of Boost.Sync is to be more lightweight than Boost.Thread and provide more synchronization primitives. Also, compatibility with multiple timing libraries. As to whether Boost.Thread would remove its synchronization primitives, I don't think it was discussed.

> I can send in a PR for CMT flavor CI if you'd like.

I think I'll add my own from Boost.Atomic, for example, when the need appears. Thanks for the offer, though.

**Comment by jeking3** [comment]
The need should be immediate, before anyone uses it. :)

**Comment by mloskot** [comment]
Plus, [given that](https://lists.boost.org/Archives/boost/2018/11/244268.php)

>  Boost.Sync was not removed but rather it was never released (yet)

this is really confusing

https://github.com/boostorg/sync/blob/e211ea428095dbdce7880973e8b56351a3ffb839/doc/changelog.qbk#L12-L17

**Comment by Lastique** [comment]
> The need should be immediate, before anyone uses it.

The primary need for CI is for testing PRs. We don't have any.

> this is really confusing

I've corrected the changelog wording.

**Comment by jeking3** [comment]
CI is best if you use it during development, so PRs are not needed after you release. :)

**Comment by dvzrv** [comment]
Is a release still happening? I'd love to either see this included in boost, or released seperately, so I can [devendor it from supercollider](https://github.com/supercollider/supercollider/issues/4361).

**Comment by Lastique** [comment]
> Is a release still happening?

Not in 1.70, unfortunately.

**Comment by cmazakas** [comment]
The echoes from the graveyard continue...
